### ISSUE TITLE
下载的格式为.jpg

### ISSUE THREAD

**Issue by jamessawyer** [loadfield/go-music#12]
在https://music.liuli.lol/上下载的格式为'.jpg',要手动改后缀，为什么不直接存为mp3格式？

**Comment by gizmo-ds** [comment]
我只见过下载后无后缀的. 后缀jpg还是第一次见.. 你把下载链接发出来看看.

**Comment by jamessawyer** [comment]
下载链接 https://p2.music.126.net/JGzMkUjAsEaL-uzK2fCJUw==/6636652186291526.mp3， 使用IDM下载， 格式为jpg

使用浏览器自带下载是没有扩展名的

**Comment by gizmo-ds** [comment]
那应该是IDM的锅, 我没办法解决.
