### ISSUE TITLE
请问下这个能获取到已被下架的音乐的真实链接原理是什么？在如果方便透漏的前提下

### ISSUE THREAD

**Issue by awkj** [loadfield/go-music#13]
之前看见你一篇博客介绍过：https://www.loadfield.com/music-loadfield
但发现最新的歌曲也能下载到，不可能是通过实时传云盘实现的，猜测应该是抓包分析了网易云的交互，尝试自己分析其中的交互，但failed，方便讲解一些分析过程么？

**Comment by gizmo-ds** [comment]
用的旧版网易云音乐安卓客户端的api接口, 具体接口代码里有.
