### ISSUE TITLE
新手求教

### ISSUE THREAD

**Issue by Uptobillion** [loadfield/go-music#19]
下载完编译文件想挂到服务器上 应该怎么做

**Comment by Uptobillion** [comment]
服务器是linux cent OS X86
感激不尽

**Comment by gizmo-ds** [comment]
conf, static, views目录上传上去, 把build目录下的go-music_linux_x86上传到conf同目录下.  
给go-music_linux_x86执行权限. 然后执行. 
改端口的话在conf/app.conf里改就行了. 

要后台执行的话可以用screen之类的, screen具体怎么用你可以Google一下.

**Comment by Uptobillion** [comment]
谢谢

**Comment by Uptobillion** [comment]
beego:can't find templatefile in the path:home.html
Request Method:	GET
Request URL:	/
RemoteAddr:	112.10.181.29
Stack
C:/Go/src/runtime/asm_386.s:498
C:/Go/src/runtime/panic.go:458
F:/GoLang/src/github.com/astaxie/beego/template.go:53
F:/GoLang/src/github.com/astaxie/beego/controller.go:245
F:/GoLang/src/github.com/astaxie/beego/controller.go:199
F:/GoLang/src/github.com/astaxie/beego/controller.go:183
F:/GoLang/src/github.com/astaxie/beego/router.go:785
C:/Go/src/net/http/server.go:2202
C:/Go/src/net/http/server.go:1579
C:/Go/src/runtime/asm_386.s:1612
beego 1.6.1 (beego framework)
golang version: go1.7
不行啊 怎么办

**Comment by gizmo-ds** [comment]
@Uptobillion 目测是执行文件路径不正确, 你确认执行文件不在"build"目录.
