### ISSUE TITLE
怎么在自己电脑上部署啊？

### ISSUE THREAD

**Issue by hoseahsu** [loadfield/go-music#2]
我想改一下，加一个一键下载歌单的功能，可是并不知道怎么在本地部署

**Comment by ivytin** [comment]
``` bash
$ mkdir $GOROOT/github.com/loadfield
$ cd $GOROOT/github.com/loadfield
$ git clone https://github.com/loadfield/go-music.git
$ go get github.com/bitly/go-simplejson
$ go get github.com/astaxie/beego
$ go build main.go
./main
```

enjoy~

---

ps: Thx @loadfield , nice work!

**Comment by hoseahsu** [comment]
Thx

**Comment by redapple0204** [comment]
@ivytin go要不要配置什么，直接装golang没法用

**Comment by ivytin** [comment]
@redapple0204 搜索golang开发环境部署即可，可参考[这篇](https://github.com/astaxie/build-web-application-with-golang/blob/master/zh/01.1.md)

**Comment by redapple0204** [comment]
@ivytin PATH设置有问题啊
>redapple@redapple ~> export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
set: Warning: path component /usr/local/sbin:/home/redapple/go/bin:/home/redapple/gopath/bin may not be valid in PATH.
set: 没有那个文件或目录
set: Did you mean 'set PATH $PATH /home/redapple/go/bin:/home/redapple/gopath/bin'?
set: Warning: path component /usr/local/bin:/home/redapple/go/bin:/home/redapple/gopath/bin may not be valid in PATH.
set: 没有那个文件或目录
set: Did you mean 'set PATH $PATH /home/redapple/go/bin:/home/redapple/gopath/bin'?
set: Warning: path component /usr/sbin:/home/redapple/go/bin:/home/redapple/gopath/bin may not be valid in PATH.
set: 没有那个文件或目录
set: Did you mean 'set PATH $PATH /home/redapple/go/bin:/home/redapple/gopath/bin'?
set: Warning: path component /usr/bin:/home/redapple/go/bin:/home/redapple/gopath/bin may not be valid in PATH.
set: 没有那个文件或目录
set: Did you mean 'set PATH $PATH /home/redapple/go/bin:/home/redapple/gopath/bin'?
set: Warning: path component /sbin:/home/redapple/go/bin:/home/redapple/gopath/bin may not be valid in PATH.
set: 没有那个文件或目录
set: Did you mean 'set PATH $PATH /home/redapple/go/bin:/home/redapple/gopath/bin'?
set: Warning: path component /bin:/home/redapple/go/bin:/home/redapple/gopath/bin may not be valid in PATH.
set: 没有那个文件或目录
set: Did you mean 'set PATH $PATH /home/redapple/go/bin:/home/redapple/gopath/bin'?
set: Warning: path component /usr/games:/home/redapple/go/bin:/home/redapple/gopath/bin may not be valid in PATH.
set: 没有那个文件或目录
set: Did you mean 'set PATH $PATH /home/redapple/go/bin:/home/redapple/gopath/bin'?
set: Warning: path component /usr/local/games:/home/redapple/go/bin:/home/redapple/gopath/bin may not be valid in PATH.
set: 没有那个文件或目录
set: Did you mean 'set PATH $PATH /home/redapple/go/bin:/home/redapple/gopath/bin'?
set: Warning: path component /snap/bin:/home/redapple/go/bin:/home/redapple/gopath/bin may not be valid in PATH.
set: 没有那个文件或目录
set: Did you mean 'set PATH $PATH /home/redapple/go/bin:/home/redapple/gopath/bin'?

**Comment by gizmo-ds** [comment]
需要配置golang编译环境.





---- On 星期四, 19 一月 2017 11:59:58 +0800 redapple0204 &lt;notifications@github.com&gt; wrote ----




@ivytin PATH设置有问题啊

redapple@redapple ~&gt; export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

 set: Warning: path component /usr/local/sbin:/home/redapple/go/bin:/home/redapple/gopath/bin may not be valid in PATH.

 set: 没有那个文件或目录

 set: Did you mean 'set PATH $PATH /home/redapple/go/bin:/home/redapple/gopath/bin'?

 set: Warning: path component /usr/local/bin:/home/redapple/go/bin:/home/redapple/gopath/bin may not be valid in PATH.

 set: 没有那个文件或目录

 set: Did you mean 'set PATH $PATH /home/redapple/go/bin:/home/redapple/gopath/bin'?

 set: Warning: path component /usr/sbin:/home/redapple/go/bin:/home/redapple/gopath/bin may not be valid in PATH.

 set: 没有那个文件或目录

 set: Did you mean 'set PATH $PATH /home/redapple/go/bin:/home/redapple/gopath/bin'?

 set: Warning: path component /usr/bin:/home/redapple/go/bin:/home/redapple/gopath/bin may not be valid in PATH.

 set: 没有那个文件或目录

 set: Did you mean 'set PATH $PATH /home/redapple/go/bin:/home/redapple/gopath/bin'?

 set: Warning: path component /sbin:/home/redapple/go/bin:/home/redapple/gopath/bin may not be valid in PATH.

 set: 没有那个文件或目录

 set: Did you mean 'set PATH $PATH /home/redapple/go/bin:/home/redapple/gopath/bin'?

 set: Warning: path component /bin:/home/redapple/go/bin:/home/redapple/gopath/bin may not be valid in PATH.

 set: 没有那个文件或目录

 set: Did you mean 'set PATH $PATH /home/redapple/go/bin:/home/redapple/gopath/bin'?

 set: Warning: path component /usr/games:/home/redapple/go/bin:/home/redapple/gopath/bin may not be valid in PATH.

 set: 没有那个文件或目录

 set: Did you mean 'set PATH $PATH /home/redapple/go/bin:/home/redapple/gopath/bin'?

 set: Warning: path component /usr/local/games:/home/redapple/go/bin:/home/redapple/gopath/bin may not be valid in PATH.

 set: 没有那个文件或目录

 set: Did you mean 'set PATH $PATH /home/redapple/go/bin:/home/redapple/gopath/bin'?

 set: Warning: path component /snap/bin:/home/redapple/go/bin:/home/redapple/gopath/bin may not be valid in PATH.

 set: 没有那个文件或目录

 set: Did you mean 'set PATH $PATH /home/redapple/go/bin:/home/redapple/gopath/bin'?
