### ISSUE TITLE
Failed - Network error?

### ISSUE THREAD

**Issue by hamiltonwei** [loadfield/go-music#7]
用chrome下载网易云音乐的时候总会提示Failed - Network error。如果右键点下载链接选另存为的话会提示 
”You don't have permission to modify files in this network location. Contact the administrator per permission to make these changes." 想问一下这是什么情况？

**Comment by gizmo-ds** [comment]
应该是资源不存在. 可以试试把下载地址的域名前缀换成http://

**Comment by hli8** [comment]
Encountered the same problem here. Still network error if I change https:// to http://

**Comment by the0demiurge** [comment]
我也是无法访问到这些资源，比如https://music.liuli.lol/music/5331885?h=on
`$curl -I http://p1.music.126.net/clDU5cCW9LmJkBocRTyBJQ==/5506354231908654.mp3`
```
HTTP/1.1 403 Forbidden
Server: ngx_openresty/1.4.3.6
Date: Fri, 11 Aug 2017 08:48:40 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive
Vary: Accept-Encoding
Set-Cookie: usertrack=ezq0almNb2h311y2CKRdAg==; expires=Sat, 11-Aug-18 08:48:40 GMT; path=/
P3P: policyref="/w3c/p3p.xml", CP="CUR ADM OUR NOR STA NID"
```
奇怪的是有的歌有的时候能下载，有的时候又下载不了

**Comment by gizmo-ds** [comment]
资源不存在的可以常试url加上或去除"h=on"
