### ISSUE TITLE
建议封装个下载工具

### ISSUE THREAD

**Issue by wenjun1055** [loadfield/go-music#8]
类似于
wget "https://p1.music.126.net/5S3_lkkBc-s3KDvt3ggmTA==/1265537883572077.mp3" -O "Stuttering.mp3"

**Comment by gizmo-ds** [comment]
好主意. 我试着写一下.

**Comment by wenjun1055** [comment]
网站是好网站，但是要批量下载太难了，得一个个的去下载

**Comment by 837468220** [comment]
现在发现这个工具也不晚

**Comment by tcpipxy** [comment]
老大 编译命令是啥啊 我编译报错

**Comment by gizmo-ds** [comment]
@tcpipxy 需要把用到的包go get下来. go build的时候会提示缺少什么包的.
